### ISSUE TITLE
Activiteiten: evenementen & producties

### ISSUE THREAD

**Issue by WimHambrouck** [DeDijlezonen/DZwelgWeb#20]
Voorbeeld van productie (= activiteit met onbeperkte duur)
![image](https://user-images.githubusercontent.com/11853615/28635654-a56c3a9a-723b-11e7-8f82-f7e33ccb93a9.png)

Voorbeeld van evenement: (= activiteit met beperkte duur)
![image](https://user-images.githubusercontent.com/11853615/28635699-d4f83dcc-723b-11e7-890e-600c3b85709f.png)

Tegoed wordt gebruikt in app om te bepalen hoe veel extra leden mogen uitgeven tijdens een evenement bezig is

**Comment by JosseKormelink** [comment]
Producties opgesplitst in evenementen en producties. Kunnen beide al worden aangemaakt. Ingeschreven leden kunnen nog niet aan evenementen worden gehangen.
